"""
simresult.py

This module provides the SimResult class, which represents the outcomes of a QLeap simulation generated by Circuit.run().
"""

def extract_counts(count_dict, indexes):
        """
        Extracts the outcomes at the given indeces from count_dict

        Returns: a dict of the extracted counts
        """

        extracted = dict()

        for outcome in count_dict:

            result = ''.join(outcome[i] for i in indexes)
            if result not in extracted:
                extracted[result] = 0

            extracted[result] += count_dict[outcome]

        return extracted

class SimResult:

    def __init__(self):
        """
        Creates a new Simresult object with no counts yet.
        """

        # Any outputs from a simulation that are added in the future should be implemented as new fields in SimResult.
        self.counts = None

    def __repr__(self):
        """
        Prints a nice representation of a SimResult.
        """
        return f'SimResult(counts: {repr(self.counts)})'
